name: Fast Dev Check

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  fast-check:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Force fast completion
    steps:
      - name: Cancel previous run
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      
      - name: Setup virtual environment
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      
      - uses: actions/cache@v3
        name: Cache dependencies
        with:
          path: ./.venv
          key: venv-dev-${{ hashFiles('poetry.lock') }}
      
      - name: Install minimal dependencies
        run: |
          poetry install --only main --no-interaction --no-ansi
      
      - name: Ultra-minimal lint (critical errors only)
        run: |
          # Install ruff if needed and run minimal check
          poetry run pip install ruff || pip install ruff
          ruff check . --select F --ignore F401,F841 || exit 1
          echo "✅ No critical syntax/import errors"
      
      - name: Fast unit tests (< 30 seconds)
        run: |
          poetry install --with dev --no-interaction --no-ansi
          poetry run pytest test/base -x --tb=short --disable-warnings -q --maxfail=3
        timeout-minutes: 1