name: Fast Dev Check

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  fast-check:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Force fast completion
    steps:
      - name: Cancel previous run
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      
      - name: Setup virtual environment
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      
      - uses: actions/cache@v3
        name: Cache dependencies
        with:
          path: ./.venv
          key: venv-dev-${{ hashFiles('poetry.lock') }}
      
      - name: Ultra-minimal lint (critical errors only)
        run: |
          # Skip poetry entirely for speed - use pip directly
          pip install ruff
          ruff check . --select F --ignore F401,F841 || exit 1
          echo "✅ No critical syntax/import errors"
      
      - name: Basic Python syntax check
        run: |
          # Just check Python can parse our files
          python -m py_compile tianshou/algorithm/multiagent/*.py || exit 1
          python -c "print('✅ All Python files can be parsed')"
        timeout-minutes: 1