name: Fast Dev Check

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  fast-check:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Force fast completion
    steps:
      - name: Cancel previous run
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      
      - name: Setup virtual environment
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      
      - uses: actions/cache@v3
        name: Cache dependencies
        with:
          path: ./.venv
          key: venv-dev-${{ hashFiles('poetry.lock') }}
      
      - name: Install dependencies
        run: |
          # Install all dependencies using poetry for consistency
          poetry install --no-interaction --no-ansi
          echo "✅ All dependencies installed"
        timeout-minutes: 3
      
      - name: Ultra-minimal lint (critical errors only)
        run: |
          # Use poetry's ruff
          poetry run ruff check . --select F --ignore F401,F841 || exit 1
          echo "✅ No critical syntax/import errors"
      
      - name: Basic Python syntax check
        run: |
          # Just check Python can parse our files
          poetry run python -m py_compile tianshou/algorithm/multiagent/*.py || exit 1
          echo "✅ All Python files can be parsed"
        timeout-minutes: 1
      
      - name: Run fast MARL tests
        run: |
          # Run all fast MARL tests using poetry's environment
          poetry run pytest test/multiagent/test_additional_coverage.py \
                 -v \
                 -x \
                 || exit 1
          echo "✅ All fast MARL tests passed"
        timeout-minutes: 2