name: MARL Tests

on:
  pull_request:
    branches:
      - master
    paths:
      # Run when MARL-related files change
      - 'tianshou/algorithm/multiagent/**'
      - 'tianshou/env/enhanced_pettingzoo_env.py'
      - 'tianshou/env/dict_observation.py'
      - 'test/multiagent/**'
      - '.github/workflows/marl_tests.yml'
  push:
    branches:
      - master
    paths:
      # Run when MARL-related files change
      - 'tianshou/algorithm/multiagent/**'
      - 'tianshou/env/enhanced_pettingzoo_env.py'
      - 'tianshou/env/dict_observation.py'
      - 'test/multiagent/**'
      - '.github/workflows/marl_tests.yml'
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false

jobs:
  marl-tests:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      matrix:
        python-version: ["3.11"]
    
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      
      - name: Cancel previous run
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      
      - name: Setup a local virtual environment
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      
      - uses: actions/cache@v3
        name: Define a cache for the virtual environment
        with:
          path: ./.venv
          key: venv-marl-${{ hashFiles('poetry.lock') }}
      
      - name: Install the project dependencies
        run: |
          poetry install --with dev
      
      - name: Run MARL fast tests
        run: |
          echo "Running fast MARL tests..."
          poetry run pytest test/multiagent/test_marl_fast_comprehensive.py -v --tb=short
      
      - name: Run MARL slow tests
        run: |
          echo "Running slow MARL tests (CTDE)..."
          poetry run pytest test/multiagent/test_ctde.py -m slow -v --tb=short
      
      - name: Run all MARL tests with coverage
        run: |
          echo "Running all MARL tests with coverage..."
          poetry run pytest test/multiagent/ -m "slow or not slow" --cov=tianshou/algorithm/multiagent --cov=tianshou/env/enhanced_pettingzoo_env --cov=tianshou/env/dict_observation --cov-report=term-missing --cov-report=xml
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV }}
          file: ./coverage.xml
          flags: marl-tests
          name: marl-coverage
          fail_ci_if_error: false